intern_management_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path("", include('main_app.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main_app/urls.py
from django.urls import path

from main_app.EditResultView import EditResultView

from . import hod_views, staff_views, intern_views, views

urlpatterns = [
    path("", views.login_page, name='login_page'),
    path("get_attendance", views.get_attendance, name='get_attendance'),
    path("firebase-messaging-sw.js", views.showFirebaseJS, name='showFirebaseJS'),
    path("doLogin/", views.doLogin, name='user_login'),
    path("logout_user/", views.logout_user, name='user_logout'),
    path("admin/home/", hod_views.admin_home, name='admin_home'),
    path("staff/add", hod_views.add_staff, name='add_staff'),
    path("department/add", hod_views.add_department, name='add_department'),
    path("send_intern_notification/", hod_views.send_intern_notification,
         name='send_intern_notification'),
    path("send_staff_notification/", hod_views.send_staff_notification,
         name='send_staff_notification'),
    path("add_shift/", hod_views.add_shift, name='add_shift'),
    path("admin_notify_intern", hod_views.admin_notify_intern,
         name='admin_notify_intern'),
    path("admin_notify_staff", hod_views.admin_notify_staff,
         name='admin_notify_staff'),
    path("admin_view_profile", hod_views.admin_view_profile,
         name='admin_view_profile'),
    path("check_email_availability", hod_views.check_email_availability,
         name="check_email_availability"),
    path("shift/manage/", hod_views.manage_shift, name='manage_shift'),
    path("shift/edit/<int:shift_id>",
         hod_views.edit_shift, name='edit_shift'),
    path("intern/view/feedback/", hod_views.intern_feedback_message,
         name="intern_feedback_message",),
    path("staff/view/feedback/", hod_views.staff_feedback_message,
         name="staff_feedback_message",),
    path("intern/view/leave/", hod_views.view_intern_leave,
         name="view_intern_leave",),
    path("staff/view/leave/", hod_views.view_staff_leave, name="view_staff_leave",),
    path("attendance/view/", hod_views.admin_view_attendance,
         name="admin_view_attendance",),
    path("attendance/fetch/", hod_views.get_admin_attendance,
         name='get_admin_attendance'),
    path("intern/add/", hod_views.add_intern, name='add_intern'),
    path("task/add/", hod_views.add_task, name='add_task'),
    path("staff/manage/", hod_views.manage_staff, name='manage_staff'),
    path("intern/manage/", hod_views.manage_intern, name='manage_intern'),
    path("department/manage/", hod_views.manage_department, name='manage_department'),
    path("task/manage/", hod_views.manage_task, name='manage_task'),
    path("staff/edit/<int:staff_id>", hod_views.edit_staff, name='edit_staff'),
    path("staff/delete/<int:staff_id>",
         hod_views.delete_staff, name='delete_staff'),

    path("department/delete/<int:department_id>",
         hod_views.delete_department, name='delete_department'),

    path("task/delete/<int:task_id>",
         hod_views.delete_task, name='delete_task'),

    path("shift/delete/<int:shift_id>",
         hod_views.delete_shift, name='delete_shift'),

    path("intern/delete/<int:intern_id>",
         hod_views.delete_intern, name='delete_intern'),
    path("intern/edit/<int:intern_id>",
         hod_views.edit_intern, name='edit_intern'),
    path("department/edit/<int:department_id>",
         hod_views.edit_department, name='edit_department'),
    path("task/edit/<int:task_id>",
         hod_views.edit_task, name='edit_task'),


    # Staff
    path("staff/home/", staff_views.staff_home, name='staff_home'),
    path("staff/apply/leave/", staff_views.staff_apply_leave,
         name='staff_apply_leave'),
    path("staff/feedback/", staff_views.staff_feedback, name='staff_feedback'),
    path("staff/view/profile/", staff_views.staff_view_profile,
         name='staff_view_profile'),
    path("staff/attendance/take/", staff_views.staff_take_attendance,
         name='staff_take_attendance'),
    path("staff/attendance/update/", staff_views.staff_update_attendance,
         name='staff_update_attendance'),
    path("staff/get_interns/", staff_views.get_interns, name='get_interns'),
    path("staff/attendance/fetch/", staff_views.get_intern_attendance,
         name='get_intern_attendance'),
    path("staff/attendance/save/",
         staff_views.save_attendance, name='save_attendance'),
    path("staff/attendance/update/",
         staff_views.update_attendance, name='update_attendance'),
    path("staff/fcmtoken/", staff_views.staff_fcmtoken, name='staff_fcmtoken'),
    path("staff/view/notification/", staff_views.staff_view_notification,
         name="staff_view_notification"),
    path("staff/result/add/", staff_views.staff_add_result, name='staff_add_result'),
    path("staff/result/edit/", EditResultView.as_view(),
         name='edit_intern_result'),
    path('staff/result/fetch/', staff_views.fetch_intern_result,
         name='fetch_intern_result'),
     path("staff/task/add/", staff_views.staff_add_task, name='staff_add_task'),
     path("staff/task/edit/<int:task_id>",
         staff_views.staff_edit_task, name='staff_edit_task'),
     path("staff/task/manage/", staff_views.staff_manage_task, name='staff_manage_task'),
     path("staff/task/delete/<int:task_id>",
         staff_views.staff_delete_task, name='staff_delete_task'),



    # Intern
    path("intern/home/", intern_views.intern_home, name='intern_home'),
    path("intern/view/attendance/", intern_views.intern_view_attendance,
         name='intern_view_attendance'),
    path("intern/apply/leave/", intern_views.intern_apply_leave,
         name='intern_apply_leave'),
    path("intern/feedback/", intern_views.intern_feedback,
         name='intern_feedback'),
    path("intern/view/profile/", intern_views.intern_view_profile,
         name='intern_view_profile'),
    path("intern/fcmtoken/", intern_views.intern_fcmtoken,
         name='intern_fcmtoken'),
    path("intern/view/notification/", intern_views.intern_view_notification,
         name="intern_view_notification"),
    path('intern/view/result/', intern_views.intern_view_result,
         name='intern_view_result'),
     path('intern/view/tasks', intern_views.view_task, name='intern_view_task'),
     path('intern/update/tasks', intern_views.update_tasks, name='update_tasks'),
     path("intern/update/tasks/<int:task_id>",
         intern_views.update_tasks, name='update_tasks')
]

main_app/models.py
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import UserManager
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.db import models
from django.contrib.auth.models import AbstractUser




class CustomUserManager(UserManager):
    def _create_user(self, email, password, **extra_fields):
        email = self.normalize_email(email)
        user = CustomUser(email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        assert extra_fields["is_staff"]
        assert extra_fields["is_superuser"]
        return self._create_user(email, password, **extra_fields)


class Shift(models.Model):
    start_time = models.TimeField(null = True)
    end_time = models.TimeField(null = True)

    def __str__(self):
        return f"From {self.start_time} to {self.end_time}" 


class CustomUser(AbstractUser):
    USER_TYPE = ((1, "HOD"), (2, "Staff"), (3, "Intern"))
    GENDER = [("M", "Male"), ("F", "Female")]
    
    
    username = None  # Removed username, using email instead
    email = models.EmailField(unique=True)
    user_type = models.CharField(default=1, choices=USER_TYPE, max_length=1)
    gender = models.CharField(max_length=1, choices=GENDER)
    profile_pic = models.ImageField()
    address = models.TextField()
    fcm_token = models.TextField(default="")  # For firebase notifications
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []
    objects = CustomUserManager()

    def __str__(self):
        return self.last_name + ", " + self.first_name


class Admin(models.Model):
    admin = models.OneToOneField(CustomUser, on_delete=models.CASCADE)



class Department(models.Model):
    name = models.CharField(max_length=120)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Staff(models.Model):
    department = models.ForeignKey(Department, on_delete=models.DO_NOTHING, null=True, blank=False)
    admin = models.OneToOneField(CustomUser, on_delete=models.CASCADE)

    def __str__(self):
        return self.admin.last_name + " " + self.admin.first_name
    
class Intern(models.Model):
    admin = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    department = models.ForeignKey(Department, on_delete=models.DO_NOTHING, null=True, blank=False)
    shift = models.ForeignKey(Shift, on_delete=models.DO_NOTHING, null=True)
    staff = models.ForeignKey(Staff, on_delete=models.DO_NOTHING, null=True, blank=False)

    def __str__(self):
        return f"{self.admin.last_name}, {self.admin.first_name} ({self.department})"


class Task(models.Model):
    name = models.CharField(max_length=120)
    intern = models.ForeignKey(Intern, on_delete=models.CASCADE, null = True)
    department = models.ForeignKey(Department, on_delete=models.CASCADE, null=True)
    description = models.TextField(blank=True)
    completed = models.BooleanField(default=False)
    intern_feedback = models.TextField(blank=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Attendance(models.Model):
    shift = models.ForeignKey(Shift, on_delete=models.DO_NOTHING, default = False)
    task = models.ForeignKey(Task, on_delete=models.DO_NOTHING, default=False)
    date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class AttendanceReport(models.Model):
    intern = models.ForeignKey(Intern, on_delete=models.DO_NOTHING)
    attendance = models.ForeignKey(Attendance, on_delete=models.CASCADE)
    status = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class LeaveReportIntern(models.Model):
    intern = models.ForeignKey(Intern, on_delete=models.CASCADE)
    date = models.CharField(max_length=60)
    message = models.TextField()
    status = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class LeaveReportStaff(models.Model):
    staff = models.ForeignKey(Staff, on_delete=models.CASCADE)
    date = models.CharField(max_length=60)
    message = models.TextField()
    status = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class FeedbackIntern(models.Model):
    intern = models.ForeignKey(Intern, on_delete=models.CASCADE)
    feedback = models.TextField()
    reply = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class FeedbackStaff(models.Model):
    staff = models.ForeignKey(Staff, on_delete=models.CASCADE)
    feedback = models.TextField()
    reply = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class NotificationStaff(models.Model):
    staff = models.ForeignKey(Staff, on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class NotificationIntern(models.Model):
    intern = models.ForeignKey(Intern, on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class InternResult(models.Model):
    intern = models.ForeignKey(Intern, on_delete=models.CASCADE)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    test = models.FloatField(default=0)
    exam = models.FloatField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


@receiver(post_save, sender=CustomUser)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        if instance.user_type == 1:
            Admin.objects.create(admin=instance)
        if instance.user_type == 2:
            Staff.objects.create(admin=instance)
        if instance.user_type == 3:
            Intern.objects.create(admin=instance)


@receiver(post_save, sender=CustomUser)
def save_user_profile(sender, instance, **kwargs):
    if instance.user_type == 1:
        instance.admin.save()
    if instance.user_type == 2:
        instance.staff.save()
    if instance.user_type == 3:
        instance.intern.save()

main_app/templates/staff_template/edit_intern_result.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}
{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                    <form method="POST">
                        {% csrf_token %}
                <div class="card card-dark">
                    <div class="card-header">
                        <h3 class="card-title">{{page_title}}</h3>
                    </div>

       
                    <!-- /.card-header -->
                    <!-- form start -->
                    <div class="card-body">


                     

                 {{ form }}

                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <button type="submit" id='update_result' class="btn btn-primary btn-block">Update Result</button>
               
                    </div>
                </form>
                </div>
                <!-- /.card -->

            </div>
        </div>
    </div>
</section>
{% endblock content %}


{% block custom_js %}
<script>
    $(document).ready(function () {
        $("#id_subject").change(function () {
            fetchStudents();
            });
            $("#id_session_year").change(function () {
                fetchStudents();
                });
   $("#id_student").change(function () {
    fetch_student_result();
                });
                $("#id_exam").hide()
                $("#id_test").hide()
                $("#update_result").hide()
                $('label[for="id_test"]').hide();
                $('label[for="id_exam"]').hide();
        function fetchStudents(){
            var subject = $("#id_subject").val()
            var session = $("#id_session_year").val()
            $("#id_student").html(null)
            if (session.length  == 0 || subject.length == 0 || session < 1 || subject < 1){
                return false;
            }
            $.ajax({
                url: "{% url 'get_students' %}",
                type: 'POST',
                data: {
                    subject: subject,
                    session:session
                }
            }).done(function (response) {
                var json_data = JSON.parse(response)
                if (json_data.length < 1) {
                    alert("No data to display")
                } else {
                    var div_data = "<option>Select Student</option>"

                    for (key in json_data) {
                        div_data += "<option value='" + json_data[key]['id'] + "'>" + json_data[key]['name'] + " </option>"
                    }
             
                    $("#id_student").html(div_data)
                }
            }).fail(function (response) {
                alert("Error in fetching students")
            })
               }

               function fetch_student_result(){
                var student = $("#id_student").val()
                var subject = $("#id_subject").val()
                $("#id_test").val(null)
                $("#id_exam").val(null)
                $("#id_exam").hide()
                $("#update_result").hide()
                $("#id_test").hide()
                $('label[for="id_test"]').hide();
                $('label[for="id_exam"]').hide();
                if (student.length  == 0 || subject.length == 0 || student < 1 || subject < 1){
                    return false;
                }
                $.ajax({
                    url: "{% url 'fetch_student_result' %}",
                    type: 'POST',
                    data: {
                        subject: subject,
                        student:student
                    }
                }).done(function (response) {
                    if (response == 'False') {
                        alert("No data to display")
                    } else {
                        var json_data = JSON.parse(response)
                        
                            $("#id_test").val(json_data['test'])
                            $("#id_exam").val(json_data['exam'])
                            $("#id_exam").show()
                            $("#id_test").show()
                            $("#update_result").show()
                            $('label[for="id_test"]').show();
                            $('label[for="id_exam"]').show();

                    }
                }).fail(function (response) {
                    alert("Error in fetching students")
                })
               }

    })
</script>
{% endblock custom_js %}

main_app/templates/staff_template/home_content.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block title %}{{page_title}}{% endblock title %}
{% block content %}
<section class="content">
    <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <div class="row">
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-info">
                    <div class="inner">
                        <h3>{{total_interns}}</h3>

                        <p>Total Interns</p>
                    </div>
                    <div class="icon">
                      <i class="nav-icon fas fa-user-graduate"></i>
                    </div>
                   
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-success">
                    <div class="inner">
                        <h3>{{total_attendance}}</h3>

                        <p>Total Attendance Taken</p>
                    </div>
                    <div class="icon">
                      <i class="nav-icon fas fa-calendar-alt"></i>
                    </div>
                   
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-maroon">
                    <div class="inner">
                        <h3>{{total_leave}}</h3>

                        <p>Total Leave Applied</p>
                    </div>
                    <div class="icon">
                      <i class="nav-icon fas fa-sign-out-alt"></i>
                    </div>
                   
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-danger">
                    <div class="inner">
                        <h3>{{total_task}}</h3>

                        <p>Total Tasks</p>
                    </div>
                    <div class="icon">
                      <i class="nav-icon fas fa-book"></i>
                    </div>
                </div>
            </div>
            <!-- ./col -->
        </div>
        <!-- /.row -->
        <!-- Main row -->
        <div class="row">
            <div class="col-md-6">
                <!-- LINE CHART -->
                <div class="card card-secondary">
                  <div class="card-header">
                    <h3 class="card-title">{{page_title}}</h3>
    
                    <div class="card-tools">
                      <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i>
                      </button>
                      <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i></button>
                    </div>
                  </div>
                  <div class="card-body">
                    <div class="chart">
                      <canvas id="pieChart" style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%;"></canvas>
                    </div>
                  </div></div>
                  <!-- /.card-body -->
                </div>
                <div class="col-md-6">
                    <div class="card card-secondary">
              <div class="card-header">
                <h3 class="card-title">{{page_title}}</h3>

                <div class="card-tools">
                  <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i>
                  </button>
                  <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i></button>
                </div>
              </div>
              <div class="card-body">
                <div class="chart">
                  <canvas id="barChart" style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%;"></canvas>
                </div>
              </div>
              <!-- /.card-body -->
            </div>
                </div>
            <!-- right col -->
        </div>
        <!-- /.row (main row) -->
    </div><!-- /.container-fluid -->
</section>
{% endblock content %}

{% block custom_js %}
  <script>
      $(document).ready(function(){
        var donutData        = {
            labels: ['Attendance', 'Leave'],
            datasets: [
              {
                data:[{{total_attendance}}, {{total_leave}}],
                backgroundColor : ['#00a65a', '#f39c12',],
              }
            ]
          }
        var pieChartCanvas = $('#pieChart').get(0).getContext('2d')
        var pieData        = donutData;
        var pieOptions     = {
          maintainAspectRatio : false,
          responsive : true,
        }
        //Create pie or douhnut chart
        // You can switch between pie and douhnut using the method below.
        var pieChart = new Chart(pieChartCanvas, {
          type: 'pie',
          data: pieData,
          options: pieOptions      
        });

        var intern_list_json = {{ intern_list_json|safe|escape }};
        var total_task_per_intern_json = {{ total_task_per_intern_json|safe|escape }};
        var completed_task_count_list = {{ completed_task_count_list|safe|escape }};

        var barChartData = {
          labels: intern_list_json,
          datasets: [
            {
              label: 'Total Tasks ',
              backgroundColor: '#17A2B8',
              borderColor: 'rgba(60,141,188,0.8)',
              data: [] // Initially empty list for total task data
            },
            {
              label: 'Completed Tasks',
              backgroundColor: '#28a745',
              borderColor: 'rgba(40,167,69,0.8)',
              data: [] // Initially empty list for completed task data
            }
          ]
        };
        
        // Loop through each intern to populate data for each dataset
        intern_list_json.forEach(function(intern, index) {
          barChartData.datasets[0].data.push(total_task_per_intern_json[index]);  // Add total task data
          barChartData.datasets[1].data.push(completed_task_count_list[index]);  // Add completed task data
        });
      
      var barChartCanvas = $('#barChart').get(0).getContext('2d');
      var stackedBarChartOptions = {
        responsive: true,
        maintainAspectRatio: false,
        scales: {
          y: {
            stacked: true,
            ticks: {
              min: 0, // Set minimum Y-axis value to 0 to ensure all bars are visible
              beginAtZero: true,
            }
          },
          x: {
            stacked: true
          }
        },
        barWidth: 0.6, // Increase bar width to improve visibility for small values
        // ... other options
      };
      Chart.scaleService.updateScaleDefaults('linear', {
        ticks: {
            min: 0
        }
    });

      
      var barChart = new Chart(barChartCanvas, {
        type: 'bar', 
        data: barChartData,
        options: stackedBarChartOptions
      });
      console.log(barChart.options.scales)
});

    
  </script>
      <!-- The core Firebase JS SDK is always required and must be listed first -->
      <script src="https://www.gstatic.com/firebasejs/7.23.0/firebase-app.js"></script>

      <!-- TODO: Add SDKs for Firebase products that you want to use
       https://firebase.google.com/docs/web/setup#available-libraries -->
      <script src="https://www.gstatic.com/firebasejs/7.23.0/firebase-analytics.js"></script>
      <script src="https://www.gstatic.com/firebasejs/7.22.1/firebase-messaging.js"></script>
  
  
      <script>
          // Your web app's Firebase configuration
          // For Firebase JS SDK v7.20.0 and later, measurementId is optional
          var firebaseConfig = {
              apiKey: "AIzaSyBarDWWHTfTMSrtc5Lj3Cdw5dEvjAkFwtM",
              authDomain: "sms-with-django.firebaseapp.com",
              databaseURL: "https://sms-with-django.firebaseio.com",
              projectId: "sms-with-django",
              storageBucket: "sms-with-django.appspot.com",
              messagingSenderId: "945324593139",
              appId: "1:945324593139:web:03fa99a8854bbd38420c86",
              measurementId: "G-2F2RXTL9GT"
          };
          // Initialize Firebase
          firebase.initializeApp(firebaseConfig)
          const messaging = firebase.messaging();
          function InitializeFireBaseMessaging() {
              messaging
                  .requestPermission()
                  .then(function () {
                      console.log("Notification Permission");
                      return messaging.getToken();
                  })
                  .then(function (token) {
                      console.log("Token : " + token);
                      sendToServer(token);
                  })
                  .catch(function (reason) {
                      console.log(reason)
                  })
          }
          messaging.onMessage(function (payload) {
              const notificationOption = {
                  body: payload.notification.body,
                  icon: payload.notification.icon,
  
              }
              if (Notification.permission == 'granted') {
                  var notification = new Notification(payload.notification.title, notificationOption);
                  notification.onclick = function (event) {
                      event.preventDefault();
                      window.open(payload.notification.click_action, "_blank");
                      notification.close();
                  }
              }
              console.log(payload);
          });
          messaging.onTokenRefresh(function () {
              messaging.getToken()
                  .then(function (newToken) {
                      console.log("New Token : " + newToken);
                      sendToServer(newToken);

                  })
                  .catch(function (reason) {
                      console.log(reason)
                  })
          })
  
          function sendToServer(token){
            $.ajax({
              url: "{% url 'staff_fcmtoken' %}",
              type: 'POST',
              data: {
                  token: token,
              }
          }).done(function (response) {
   
             
          }).fail(function (response) {
          })

          }
          
          InitializeFireBaseMessaging();
      </script>
{% endblock custom_js %}

main_app/templates/staff_template/staff_add_task_template.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block title %}{{page_title}}{% endblock%}

{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-dark">
                    <div class="card-header">
                        <h3 class="card-title">{{page_title}}</h3>
                    </div>

                    {% include "main_app/form_template.html" with messages=messages  form=form button_text="Add Task" interns=interns%}
                </div>
                <!-- /.card -->

            </div>
        </div>
    </div>
</section>
{% endblock content %}

main_app/templates/staff_template/staff_edit_task_template.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block title %}{{page_title}}{% endblock %}

{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-dark">
                    <div class="card-header">
                        <h3 class="card-title">{{page_title}}</h3>
                    </div>

                    {% include "main_app/form_template.html" with messages=messages  form=form button_text="Edit Task"%}
                </div>
                <!-- /.card -->

            </div>
        </div>
    </div>
</section>
{% endblock content %}